<?php

namespace Phiil\GoogleSheetsTranslationBundle\Tests\Fixtures;

use Symfony\Component\DependencyInjection\ContainerBuilder;

class TestSheetKernel extends TestKernel
{
    /**
     * Add kernel.secret because some packages depend on it
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->setParameter('googlesheets_translations.sheet.publicId', '1E9r6LCSeQV6rrEVq2YuSnm1OEbbTjgc50G9OHHUvihk');
    }
}
